---
title: "Lab 6"
author: "Anna Talken"
date: "2/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(sf)
library(tmap)
library(gstat)
library(stars)
```


```{r}
ca_dgw <- read_sf(here("ca_dgw"), layer = "F2013_DBGS_Points_20150720_093252") %>% 
  clean_names()

st_crs(ca_dgw)

ca_counties <- read_sf(here("ca_counties"), layer = "CA_Counties_TIGER2016") %>% 
  clean_names() %>% 
  select(name)


st_crs(ca_counties)

ca_counties <- st_transform(ca_counties, st_crs(ca_dgw)) #transforms the crs of the second data frame to match the ca_dgw df CRS (EPSG 4326)

st_crs(ca_counties)
```

```{r}
#use geom_sf to add the layers to ggplot
ggplot() +
  geom_sf(data = ca_counties) +
  geom_sf(data = ca_dgw, aes(color = dgbs)) +
  theme_minimal()
```

```{r}
#Creating an interactive map
tmap_mode("view")

tm_shape(ca_dgw) +
  tm_dots("dgbs")
```

```{r}
#creates df with polygon for san joaquin county
sj_county <- ca_counties %>% 
  filter(name == "San Joaquin")

#creates df with SJ ground water observations
sj_depth <- ca_dgw %>% 
  st_intersection(sj_county)

ggplot() +
  geom_sf(data = sj_county) +
  geom_sf(data = sj_depth, aes(color = dgbs))
```

```{r}
#check for duplications at a single point (this will mess up krieging if there are multiple points at the exact same spot)
well_duplicates <- sj_depth %>% 
  get_dupes(latitude, longitude)

sj_depth <- sj_depth %>% 
  filter(!local_well %in% well_duplicates$local_well) #filter to keep observations where local well number is NOT in one of the duplicates - omits 4 wells from df
```

Create a variogram (we get info for how much weight each observation gets for a prediction at a new location)

```{r}
sj_dgw_vgm <- variogram(dgbs ~ 1, data = sj_depth)
plot(sj_dgw_vgm)

#nugget is measure of semivariance at small distances
sj_dgw_vgm_fit <- fit.variogram(sj_dgw_vgm, model= (
  vgm(nugget = 20, psill = 3000, range = 30, model = "Gau")
))


plot(sj_dgw_vgm, sj_dgw_vgm_fit)
```

Spatial Kriging (interpolation)

```{r}
sj_grid <- st_bbox(sj_county) %>% #minimum and max values for long and lat for sj county
  st_as_stars(dx = 0.01, dy = 0.01) %>% 
  st_set_crs(4326) %>% # sets CRS 
  st_crop(sj_county) #creates grid just over san joaquin county

plot(sj_grid)

#What is estimated depth of groundwater over each pixel?
```

```{r}
sj_dgw_krige <- krige(dgbs ~ 1, sj_depth, sj_grid, model = sj_dgw_vgm_fit)

plot(sj_dgw_krige) #allows us to see based on existing observations, what our variogram will predict for depth of groundwater across the entire county
```











